parameters:
    pim_custom_entity.action.factory.class:      Pim\Bundle\CustomEntityBundle\Action\ActionFactory
    pim_custom_entity.action.index.class:        Pim\Bundle\CustomEntityBundle\Action\IndexAction
    pim_custom_entity.action.delete.class:       Pim\Bundle\CustomEntityBundle\Action\DeleteAction
    pim_custom_entity.action.create.class:       Pim\Bundle\CustomEntityBundle\Action\CreateAction
    pim_custom_entity.action.quick_create.class: Pim\Bundle\CustomEntityBundle\Action\QuickCreateAction
    pim_custom_entity.action.edit.class:         Pim\Bundle\CustomEntityBundle\Action\EditAction
    pim_custom_entity.action.show.class:         Pim\Bundle\CustomEntityBundle\Action\ShowAction
    pim_custom_entity.action.history.class:      Pim\Bundle\CustomEntityBundle\Action\HistoryAction
    pim_custom_entity.action.mass_edit.class:    Pim\Bundle\CustomEntityBundle\Action\MassEditAction
    pim_custom_entity.action.mass_delete.class:  Pim\Bundle\CustomEntityBundle\Action\MassDeleteAction
    pim_custom_entity.action.quick_export.class: Pim\Bundle\CustomEntityBundle\Action\QuickExportAction

services:
    pim_custom_entity.action.factory:
        class: %pim_custom_entity.action.factory.class%
        arguments:
            - @service_container
            - @pim_custom_entity.configuration.registry

    pim_custom_entity.action:
        abstract: true
        arguments:
            - @pim_custom_entity.action.factory
            - @pim_custom_entity.action_event_manager
            - @pim_custom_entity.manager.registry
            - @router
            - @translator

    pim_custom_entity.action.mass_delete:
        class: %pim_custom_entity.action.mass_delete.class%
        parent: pim_custom_entity.action.viewable
        scope: prototype

    pim_custom_entity.action.viewable:
        abstract: true
        parent: pim_custom_entity.action
        arguments:
            - @templating

    pim_custom_entity.action.show:
        class: %pim_custom_entity.action.show.class%
        parent: pim_custom_entity.action.viewable

    pim_custom_entity.action.history:
        class: %pim_custom_entity.action.history.class%
        parent: pim_custom_entity.action.viewable

    pim_custom_entity.action.index:
        class: %pim_custom_entity.action.index.class%
        parent: pim_custom_entity.action.viewable
        scope: prototype

    pim_custom_entity.action.delete:
        class: %pim_custom_entity.action.delete.class%
        parent: pim_custom_entity.action
        scope: prototype

    pim_custom_entity.action.form:
        abstract: true
        parent: pim_custom_entity.action.viewable
        arguments:
            - @form.factory

    pim_custom_entity.action.edit:
        class: %pim_custom_entity.action.edit.class%
        parent: pim_custom_entity.action.form
        scope: prototype

    pim_custom_entity.action.mass_edit:
        class: %pim_custom_entity.action.mass_edit.class%
        parent: pim_custom_entity.action.form
        scope: prototype
        arguments:
            - @pim_custom_entity.mass_action.datagrid_query_generator
            - @pim_custom_entity.mass_action.mass_updater

    pim_custom_entity.action.quick_export:
        class: %pim_custom_entity.action.quick_export.class%
        parent: pim_custom_entity.action
        scope: prototype
        arguments:
            - @pim_datagrid.extension.mass_action.dispatcher
            - @pim_import_export.repository.job_instance
            - @pim_connector.launcher.simple_job_launcher
            - @security.token_storage

    pim_custom_entity.action.create:
        class: %pim_custom_entity.action.create.class%
        parent: pim_custom_entity.action.form
        scope: prototype

    pim_custom_entity.action.quick_create:
        class: %pim_custom_entity.action.quick_create.class%
        parent: pim_custom_entity.action.form
        scope: prototype
