parameters:
    pim_custom_entity.reader.database.reference_data.class: Pim\Bundle\CustomEntityBundle\Connector\Reader\Database\ReferenceDataReader

    pim_custom_entity.processor.denormalization.reference_data.class: Pim\Bundle\CustomEntityBundle\Connector\Processor\Denormalization\Processor
    pim_custom_entity.processor.normalization.reference_data.class: Pim\Bundle\CustomEntityBundle\Connector\Processor\Normalization\Processor

    pim_custom_entity.mass_edit_connector.reader.reference_data.class: Pim\Bundle\CustomEntityBundle\MassEditConnector\Reader\ReferenceDataReader
    pim_custom_entity.mass_edit_connector.processor.reference_data_to_flat_array.class: Pim\Bundle\CustomEntityBundle\MassEditConnector\Processor\ReferenceDataToFlatArrayProcessor
    pim_custom_entity.mass_edit_connector.writer.reference_data.class: Pim\Bundle\CustomEntityBundle\MassEditConnector\Writer\ReferenceDataWriter


services:
    # Readers
    pim_custom_entity.reader.file.csv:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.dummy'

    pim_custom_entity.reader.database.reference_data:
        class: '%pim_custom_entity.reader.database.reference_data.class%'
        arguments:
            - '@pim_custom_entity.configuration.registry'
            - '@doctrine.orm.entity_manager'

    # Processors
    pim_custom_entity.processor.denormalization.reference_data:
        class: '%pim_custom_entity.processor.denormalization.reference_data.class%'
        arguments:
            - '@pim_custom_entity.configuration.registry'
            - '@doctrine.orm.entity_manager'
            - '@pim_custom_entity.updater.custom_entity'
            - '@validator'
            - '@akeneo_storage_utils.doctrine.object_detacher'

    pim_custom_entity.processor.normalization.reference_data:
        class: '%pim_custom_entity.processor.normalization.reference_data.class%'
        arguments:
            - '@property_accessor'
            - '@pim_serializer'

    # Writers
    pim_custom_entity.writer.database.custom_entity:
        class: '%pim_connector.writer.database.class%'
        arguments:
            - '@pim_custom_entity.saver.custom_entity'
            - '@akeneo_storage_utils.doctrine.object_detacher'

    pim_custom_entity.writer.file.csv_reference_data:
        class: '%pim_connector.writer.file.csv.class%'
        arguments:
            - '@pim_connector.array_converter.dummy'
            - '@pim_connector.factory.flat_item_buffer'
            - '@pim_connector.writer.file.flat_item_buffer_flusher'


    # Quick export connector
    pim_custom_entity.mass_edit_connector.reader.reference_data:
        class: %pim_custom_entity.mass_edit_connector.reader.reference_data.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @pim_reference_data.registry

    pim_custom_entity.mass_edit_connector.processor.reference_data_to_flat_array:
        class: %pim_custom_entity.mass_edit_connector.processor.reference_data_to_flat_array.class%
        arguments:
            - @pim_serializer

    pim_custom_entity.mass_edit_connector.processor.reference_data_writer:
        class: %pim_custom_entity.mass_edit_connector.writer.reference_data.class%
        parent: pim_connector.writer.file.csv
