parameters:
    pim_custom_entity.mass_action.mass_updater.class: Pim\Bundle\CustomEntityBundle\MassAction\MassUpdater

services:
    pim_custom_entity.mass_action.mass_updater:
        class: '%pim_custom_entity.mass_action.mass_updater.class%'
        arguments:
            - '@doctrine'

    pim_custom_entity.mass_action.mass_action.handler.edit:
        class: '%pim_datagrid.extension.mass_action.handler.edit.class%'
        arguments:
            - '@pim_datagrid.datasource.result_record.hydrator.object_id'
            - '@event_dispatcher'
        tags:
            -
                name: pim_datagrid.extension.mass_action.handler
                alias: custom_mass_edit
                operation_group: mass-edit

    pim_custom_entity.mass_action.mass_action.handler.quick_export:
        class: '%pim_datagrid.extension.mass_action.handler.export.class%'
        arguments:
            - '@pim_datagrid.datasource.result_record.hydrator.object_id'
            - '@event_dispatcher'
        tags:
            -
                name: pim_datagrid.extension.mass_action.handler
                alias: custom_quick_export
