config:
    paths:
        custom_entity/field/select2: pimcustomentity/js/field/select2
        custom_entity/field/custom-entity-select: pimcustomentity/js/field/custom-entity-select
        custom_entity/form/creation/modal: pimcustomentity/js/form/creation/modal
        custom_entity/form/common/edit-form: pimcustomentity/js/form/common/edit-form
        custom_entity/form/common/entity-saver: pimcustomentity/js/form/common/entity-saver
        custom_entity/form/common/save-form: pimcustomentity/js/form/common/save-form
        custom_entity/form/common/delete: pimcustomentity/js/form/common/delete
        custom_entity/form/common/label: pimcustomentity/js/form/common/label
        custom_entity/controller/list: pimcustomentity/js/controller/custom_entity-list
        custom_entity/controller/edit: pimcustomentity/js/controller/custom_entity-edit
        custom_entity/fetcher: pimcustomentity/js/fetcher/custom_entity-fetcher
        custom_entity/remover/reference-data: pimcustomentity/js/remover/reference-data-remover

    config:
        pim/fetcher-registry:
            fetchers:
                custom_entity:
                    module: custom_entity/fetcher
                    options:
                        urls:
                            list: pim_customentity_rest_list
                            get: pim_customentity_rest_get
                            getall: pim_customentity_rest_getall

        pim/controller-registry:
            controllers:
                pim_customentity_index:
                    module: custom_entity/controller/list
                pim_customentity_rest_get:
                    module: custom_entity/controller/edit
