parameters:
    pim_custom_entity.normalizer.referable.class: Pim\Bundle\CustomEntityBundle\Normalizer\ReferableNormalizer
    pim_custom_entity.normalizer.custom_entity.class: Pim\Bundle\CustomEntityBundle\Normalizer\CustomEntityNormalizer
    pim_custom_entity.normalizer.standard.minimal.class: Pim\Bundle\CustomEntityBundle\Normalizer\Standard\MinimalStandardNormalizer

services:
    pim_custom_entity.normalizer.referable:
        class: '%pim_custom_entity.normalizer.referable.class%'
        arguments:
            - ['csv', 'flat']
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 100 }
            - { name: pim_serializer.normalizer, priority: 100 }

    pim_custom_entity.normalizer.internal_api.custom_entity:
        class: '%pim_custom_entity.normalizer.custom_entity.class%'
        arguments:
            - '@pim_serializer'

    pim_custom_entity.normalizer.standard.minimal:
        public: false
        class: '%pim_custom_entity.normalizer.standard.minimal.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 150 }

    pim_custom_entity.array_converter.flat_to_standard.reference_data:
       class: Pim\Bundle\CustomEntityBundle\ArrayConverter\FlatToStandard\ReferenceData
       arguments:
           - '@pim_connector.array_convertor.checker.fields_requirement'
           - ['code']
           - ['code']
