parameters:
    pim_custom_entity.configuration.registry.class: Pim\Bundle\CustomEntityBundle\Configuration\Registry
    pim_custom_entity.configuration.default.class:  Pim\Bundle\CustomEntityBundle\Configuration\Configuration
    pim_custom_entity.controller.class:             Pim\Bundle\CustomEntityBundle\Controller\Controller
    pim_custom_entity.manager.class:                Pim\Bundle\CustomEntityBundle\Manager\Manager
    pim_custom_entity.manager.registry.class:       Pim\Bundle\CustomEntityBundle\Manager\Registry
    pim_custom_entity.action_event_manager.class:   Pim\Bundle\CustomEntityBundle\Event\ActionEventManager
    pim_custom_entity.datasource.result_record.hydrator.object_id.class: Pim\Bundle\DataGridBundle\Datasource\ResultRecord\Orm\ObjectIdHydrator
    pim_custom_entity.repository.attribute.class: Pim\Bundle\CustomEntityBundle\Entity\Repository\AttributeRepository

services:
    pim_custom_entity.configuration.registry:
        class: %pim_custom_entity.configuration.registry.class%
        arguments:
            - '@service_container'

    pim_custom_entity.action_event_manager:
        class: %pim_custom_entity.action_event_manager.class%
        arguments:
            - '@event_dispatcher'

    pim_custom_entity.datasource.result_record.hydrator.object_id:
        class: '%pim_custom_entity.datasource.result_record.hydrator.object_id.class%'

    pim_custom_entity.extension.mass_action.handler.delete:
        class: '%pim_datagrid.extension.mass_action.handler.delete.class%'
        arguments:
            - '@pim_custom_entity.datasource.result_record.hydrator.object_id'
            - '@translator'
            - '@event_dispatcher'
        tags:
            - { name: pim_datagrid.extension.mass_action.handler, alias: custom_entity_mass_delete }

    pim_custom_entity.repository.attribute:
        class: '%pim_custom_entity.repository.attribute.class%'
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '%pim_catalog.entity.attribute.class%'
