language: php

php:
    - "5.6"

dist: precise

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - phpenv config-add travis.php.ini
    - phpenv config-rm xdebug.ini || echo "xdebug not available for PHP $TRAVIS_PHP_VERSION"
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
    - composer update --no-interaction --no-scripts --prefer-dist

script:
    - ./bin/phpspec run
