akeneo_pim_structure:
    reference_data:
        fabrics:
            class: Acme\Bundle\CustomBundle\Entity\Fabric
            type: multi
        color:
            class: Acme\Bundle\CustomBundle\Entity\Color
            type: simple
        brand:
            class: Acme\Bundle\CustomBundle\Entity\Brand
            type: multi
        pictogram:
            class: Acme\Bundle\CustomBundle\Entity\Pictogram
            type: simple