extensions:
    reference-data-job-instance-csv-export-edit-permission:
        module: pimee/common/tab/permission
        parent: reference-data-job-instance-csv-export-edit-tabs
        targetZone: container
        aclResourceId: pimee_importexport_export_profile_edit_permissions
        position: 115
        config:
            title: pimee_enrich.form.job_instance.tab.permission.title
            entity: job_instance
            tabCode: pim-job-instance-permission

    reference-data-job-instance-csv-export-show-permission:
        module: pimee/common/tab/permission
        parent: reference-data-job-instance-csv-export-show-tabs
        targetZone: container
        position: 115
        aclResourceId: pimee_importexport_export_profile_show_permissions
        config:
            title: pimee_enrich.form.job_instance.tab.permission.title
            entity: job_instance
            tabCode: pim-job-instance-permission
            readOnly: true

    reference-data-job-instance-csv-import-edit-permission:
        module: pimee/common/tab/permission
        parent: reference-data-job-instance-csv-import-edit-tabs
        targetZone: container
        aclResourceId: pimee_importexport_import_profile_edit_permissions
        position: 115
        config:
            title: pimee_enrich.form.job_instance.tab.permission.title
            entity: job_instance
            tabCode: pim-job-instance-permission

    reference-data-job-instance-csv-import-show-permission:
        module: pimee/common/tab/permission
        parent: reference-data-job-instance-csv-import-show-tabs
        targetZone: container
        aclResourceId: pimee_importexport_import_profile_show_permissions
        position: 115
        config:
            title: pimee_enrich.form.job_instance.tab.permission.title
            entity: job_instance
            tabCode: pim-job-instance-permission
