datagrid:
    fabric:
        options:
            entityHint: fabric
            manageFilters: false
        source:
            type: pim_datasource_default
            entity: Acme\Bundle\CustomBundle\Entity\Fabric
            repository_method: createDatagridQueryBuilder
        columns:
            code:
                label: Code
            name:
                label: name
        properties:
            id: ~
            edit_link:
                type: url
                route: pim_customentity_edit
                params:
                    - id
                    - customEntityName
            delete_link:
                type: url
                route: pim_customentity_rest_delete
                params:
                    - id
                    - customEntityName
        actions:
            edit:
                type:      navigate
                label:     Edit the reference data
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: Delete the reference data
                icon:  trash
                link:  delete_link
        sorters:
            columns:
                code:
                    data_name: rd.code
                name:
                    data_name: rd.name
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
        filters:
            columns:
                name:
                    type:      search
                    label:     Name
                    data_name: rd.name
                code:
                    type:      string
                    label:     Code
                    data_name: rd.code
