datagrid:
    pictogram:
        extends: translatable-entity-grid
        options:
            entityHint: pictogram
            manageFilters: false
            locale_parameter: localeCode
        source:
            type: pim_datasource_default
            entity: Acme\Bundle\CustomBundle\Entity\Pictogram
            repository_method: createDatagridQueryBuilder
        columns:
            code:
                label: Code
            label:
                label: Label
            created:
                label: Created
                type: product_value_datetime
                frontend_type: datetime
            updated:
                label: Updated
                type: product_value_datetime
                frontend_type: datetime
        properties:
            id: ~
            edit_link:
                type: url
                route: pim_customentity_rest_get
                params:
                    - id
                    - customEntityName
            delete_link:
                type: url
                route: pim_customentity_rest_delete
                params:
                    - id
                    - customEntityName
        actions:
            edit:
                type:      navigate
                label:     Edit the reference data
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: Delete the reference data
                icon:  trash
                link:  delete_link
        sorters:
            columns:
                code:
                    data_name: rd.code
                label:
                    data_name: translation.label
                created:
                    data_name: rd.created
                updated:
                    data_name: rd.udapted
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: rd.code
                label:
                    type:      search
                    label:     Label
                    data_name: translation.label
                created:
                    type:             date
                    label:            Created
                    data_name:        rd.created
                    filter_by_having: true
                updated:
                    type:             date
                    label:            Updated
                    data_name:        rd.udapted
                    filter_by_having: true
