extensions:
    pim-brand-create-modal:
        module: custom_entity/form/creation/modal
        config:
            labels:
               title: pim_custom_entity.create_popin.title
               subTitle: acme_custom.menu.item.reference_data.brand
            successMessage: pim_custom_entity.message.created
            editRoute: pim_customentity_edit
            postUrl:
                route: pim_customentity_rest_create
                parameters:
                    customEntityName: brand

    pim-brand-create-code:
        module: pim/form/common/creation/field
        parent: pim-brand-create-modal
        targetZone: fields
        position: 10
        config:
            identifier: code
            label: pim_custom_entity.form.field.label.code
